# qemutest/justfile

disk := "disk.qcow"
size := "20"
memory := "4G"
cpus := "4"
ssh_port := "2022"
ovmf_code := "/usr/share/edk2-ovmf/x64/OVMF_CODE.fd"
ovmf_vars := "/usr/share/edk2-ovmf/x64/OVMF_VARS.fd"
ovmf_vars_local := "OVMF_VARS.fd"

# Create a qcow2 disk. Default name: disk.qcow, default size: 20G.
create_disk name=disk size=size:
    qemu-img create -f qcow2 {{name}} {{size}}G

# Launch VM with UEFI, 4 CPU, 4G RAM, host network, and SSH port forward.
# Requires an ISO path as argument. Default disk: disk.qcow.
install_arch iso disk=disk:
    [ -f {{ovmf_vars_local}} ] || cp {{ovmf_vars}} {{ovmf_vars_local}}
    qemu-system-x86_64 \
        -enable-kvm \
        -m {{memory}} \
        -smp {{cpus}} \
        -cpu host \
        -drive if=pflash,format=raw,readonly=on,file={{ovmf_code}} \
        -drive if=pflash,format=raw,file={{ovmf_vars_local}} \
        -drive file={{disk}},format=qcow2,if=virtio \
        -cdrom {{iso}} \
        -nic user,hostfwd=tcp::{{ssh_port}}-:22 \
        -boot d

# Launch VM without ISO. Default disk: disk.qcow.
launch_arch disk=disk:
    [ -f {{ovmf_vars_local}} ] || cp {{ovmf_vars}} {{ovmf_vars_local}}
    qemu-system-x86_64 \
        -enable-kvm \
        -m {{memory}} \
        -smp {{cpus}} \
        -cpu host \
        -drive if=pflash,format=raw,readonly=on,file={{ovmf_code}} \
        -drive if=pflash,format=raw,file={{ovmf_vars_local}} \
        -drive file={{disk}},format=qcow2,if=virtio \
        -nic user,hostfwd=tcp::{{ssh_port}}-:22
